services:
  bluesky-site:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.bluesky-site.loadbalancer.server.port=80

      - traefik.http.routers.bluesky-prod.rule=Host(`blueskytravelmx.com`) || Host(`www.blueskytravelmx.com`)
      - traefik.http.routers.bluesky-prod.entrypoints=web,websecure
      - traefik.http.routers.bluesky-prod.tls=true
      - traefik.http.routers.bluesky-prod.tls.certresolver=mytlschallenge
      - traefik.http.routers.bluesky-prod.service=bluesky-site

      - traefik.http.routers.vps-yoga-verde.rule=Host(`yoga-verde.srv1175749.hstgr.cloud`)
      - traefik.http.routers.vps-yoga-verde.entrypoints=web,websecure
      - traefik.http.routers.vps-yoga-verde.tls=true
      - traefik.http.routers.vps-yoga-verde.tls.certresolver=mytlschallenge
      - traefik.http.routers.vps-yoga-verde.service=bluesky-site
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: n8n_default
